export const _CHANGELOG={
    "v":"v0.25.4",
    "d":"9/22/2025",
    "cm":"i made half of these modifications during class so excuse their quality",
    "c":[
      "NOTICE!!! I know a lot of the games are broken, it's a side effect of the new technology. I AM working on it, hence the status checker. I'm mostly reviewing through current games, checking which ones, and marking their status so I can fix them in one big update",
      "Code reorginize",
      "Implement status checker to games in Beanpowered",
      "Added description to every game",
      "Game verification x2. Games have been marked with their working status and will be promptly updated",
      "Started custom wallpaper import script",
      "Pathced a few bugs with vite and vercel",
      "Fixed Analytic bugs",
      "Added more tips",
      "Set Up Firebase",      
      "Added Custom CSS Feature",
      "Multiple Bug Fixes",
      "Added Pink Theme",
      "Added Red Theme",
      "Added Purple Theme",
      "Added Mint Theme",
      "Added Forest Theme",
      "Added Ocean Theme",
      "Added Firebase Studio stuff (like nix)",
      "Fixed yarn on nix",
      "Finally Added Loading Screen",
      "Fixed half of the games list",
      "my dumbass forgot to implement the solaris command (oops)",
      "Added Functionality to Start Menu",
    ]
  };