export const _CHANGELOG={
  "v":"v1.28.19",
  "d":"10/17/2025",
  "cm":"BLOG OUT NOW",
  "c":[
    "Added White Theme",
    "Animation quickfixes",
    "Fixed organization and component order issues in Settings.jsx",
    "Added blog",
    "Fixed storage issues with localStorage by replacing direct src refrence with object pointer",
    "firebase additions",
    "description addition",
    "Fixed version ## + typos",
    "Bumped to version +1.**.**",
    "Started vercel blob implementation (which should hopefully allow for more wallpaper storage)",
    "Fixed indentation on games.js",
    "Duplicated keys bugfix",
    "Quick theme font color fix",
    "UI Tweaks to Beanpowered",
    "Optimized all images at build (via vite-plugin-image-optimizer)",
    "FIXED ALL FLASH GAMES !! (it was deadass a url parzmeter bug of all things)",
    "Reviewed and added statuses to multiple games (batch 18,25,+26)",
    "Fixed wallpaper upload!! (fucking finally)",
    "Added more wallpapers",
    "Added Storage Bar",
    "NOTICE!!! I know a lot of the games are broken, it's a side effect of the new technology. I AM working on it, hence the status checker. I'm mostly reviewing through current games, checking which ones, and marking their status so I can fix them in one big update",
  ]
};