export const _CHANGELOG={
    "v":"v0.23.4",
    "d":"9/16/2025",
    "cm":"i made half of these modifications during class so excuse their quality",
    "c":[
      "Code reorginize",
      "Started custom wallpaper import script",
      "Pathced a few bugs with vite and vercel",
      "Fixed Analytic bugs",
      "Added more tips",
      "Set Up Firebase",      
      "Added Custom CSS Feature",
      "Multiple Bug Fixes",
      "Added Pink Theme",
      "Added Red Theme",
      "Added Purple Theme",
      "Added Mint Theme",
      "Added Forest Theme",
      "Added Ocean Theme",
      "Added Firebase Studio stuff (like nix)",
      "Fixed yarn on nix",
      "Finally Added Loading Screen",
      "Fixed half of the games list",
      "my dumbass forgot to implement the solaris command (oops)",
      "Added Functionality to Start Menu",
    ]
  };